# Generated by Django 5.2.6 on 2025-09-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_id', models.CharField(max_length=20)),
                ('Doctor_name', models.CharField(max_length=100)),
                ('Doctor_email', models.EmailField(max_length=254)),
                ('Doctor_contact', models.CharField(max_length=20)),
            ],
        ),
    ]
